services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:8000
    environment:
      - DB_HOST_NAME = postgres
      - DB_PORT = 5432
      - DB_PASSWORD = 4343
      - DB_NAME = fastapi
      - DB_USERNAME = postgres
      - SECRET_KEY = e36d043de0672695e6d54379c58455db9bc242ac67f34f818b30867d026ab0b9
      - ALGORITHM = HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES = 60

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=4343
      - POSTGRES_DB = fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
